config/routes.rb
Rails.application.routes.draw do
  root 'portal_page#home'

  devise_for :users

  resources :topics do
    resources :posts
  end

  resources :posts do
    resources :comments, shallow: true
    member do
      post 'top' => "posts#top"
      post 'elite' => "posts#elite"
    end
    collection do
      get 'elite' => "posts#elite_posts"
    end
  end

  post "posts/post_pictures" => "posts#pictures"
  post "posts/:id/post_pictures" => "posts#pictures"
  post "post_pictures" => "posts#pictures"

  resources :users, only: [:index, :show]
  get "avatar" => "users#avatar"
  patch "avatar" => "users#update"

  resources :shops do
    resources :foods, shallow: true
    resources :shop_remarks, shallow: true
    member do
      get "uppics" => "shops#uppics"
      post "uppics" => "shops#upload_picture"
      post "face" => "shops#face"
      post "check" => "shops#check"
    end
    collection do
      get "owner" => "shops#owner"
    end
  end

  get "foods" => "foods#index_all"
  post "foods/:id/check" => "foods#check", as: :check_food
  post "foods/:food_id/food_remarks" => "food_remarks#create", as: :food_food_remarks
  delete "food_remarks/:id" => "food_remarks#destroy", as: :food_remark
  resources :remarks

  get "category/:category_id/shops" => "shops#index", as: :category_shops

  resources :pictures, only: [:destroy]

  namespace :admin do
    get 'manage/check'
    get 'manage/shops'
  end

  post "shops/likes/:likable_id/:likable_type" => "likes#create", as: :shop_likes
  post "foods/likes/:likable_id/:likable_type" => "likes#create", as: :food_likes

end

app/models/shop.rb
class Shop < ActiveRecord::Base
  validates :name, :description, :state, :user_id, :area_id,
            :category_id, presence: true

  belongs_to :area
  belongs_to :user
  belongs_to :category, -> { where kind: Category::CATEGORY_KIND[:shop] }
  belongs_to :face, class_name: "Picture", foreign_key: :face_id, dependent: :destroy
  has_many :foods, -> { where state: 1 }, dependent: :destroy
  has_one :address,  dependent: :destroy
  has_many :pictures, as: :imageable, dependent: :destroy
  has_many :shop_remarks, dependent: :destroy
  has_many :likes, as: :likable, dependent: :destroy

  accepts_nested_attributes_for :address

  default_scope -> { order created_at: :desc }

  STATE = ["待审核", "正常"]

  # will_paginate
  self.per_page = 100
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: [:face, :upload_picture, :uppics, :show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # cancancan
  load_and_authorize_resource

  layout "shops_layout"

  # GET /shops
  # GET /shops.json
  def index
    @categories = Category.shop_categories
    if params[:category_id].nil?
      @shops = Shop.where("state != 0").paginate(:page => params[:page])
    else
      @category = Category.find params[:category_id]
      @shops = @category.shops.paginate(:page => params[:page])
    end
  end

  def owner
    @shops = current_user.shops
  end

  # GET /shops/1
  # GET /shops/1.json
  def show
    @remarks = @shop.shop_remarks.order(created_at: :desc).paginate(:page => params[:page])
  end

  # GET /shops/new
  def new
    @shop = Shop.new
    @shop.build_address
  end

  # GET /shops/1/edit
  def edit
  end

  # POST /shops
  # POST /shops.json
  def create
    # state 0 means shop is invaliable
    @shop = current_user.shops.new(shop_params.merge state: 0)

    respond_to do |format|
      if @shop.save
        format.html { redirect_to uppics_shop_url(@shop), notice: 'Shop was successfully created.' }
        format.json { render :show, status: :created, location: @shop }
      else
        format.html { render :new }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shops/1
  # PATCH/PUT /shops/1.json
  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to @shop, notice: 'Shop was successfully updated.' }
        format.json { render :show, status: :ok, location: @shop }
      else
        format.html { render :edit }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1
  # DELETE /shops/1.json
  def destroy
    @shop.destroy
    respond_to do |format|
      format.html { redirect_to shops_url, notice: 'Shop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /shops/1/uppics
  def uppics
  end
  # POST /shops/1/upload_picture
  def upload_picture
    @picture = @shop.pictures.create image: params[:shop][:image]

    if @picture
      if @shop.face.nil?
        @shop.face = @shop.pictures.first
        @shop.save
      end
      render "upload_picture"
      # render json: {pic_path: @picture.image.url(:small), message: "upload success"}
    else
      render js: "alert(upload failed)"
      # render json: {message: "upload fail"}
    end
  end

  # POST /shops/1/face
  def face
    @shop.face_id = params[:picture_id]
    if @shop.save
      render json: {message: "设置成功"}
    end
  end

  def check
    @shop.update state: 1
    respond_to do |format|
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = Shop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shop_params
      params.require(:shop).permit(:name, :description, :state, :area_id, :category_id,
                                   :telephone, :contact, :user_id, :face_id, :address_attributes => [:name])
    end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/_form.html.erb
<%= simple_form_for(@shop) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :area, prompt: false, label: "选择市县" %>
    <%= f.association :category, label: "选择店铺类型" %>
    <%= f.input :name, label: "店铺名称" %>

	<%= f.simple_fields_for :address_attributes, @shop.address do |fd| %>
	  <%= fd.input :name, label: "地址" %>
	<% end %>

    <%= f.input :description, label: "店铺说明" %>
    <%= f.input :telephone, label: "联系电话" %>
    <%= f.input :contact, label: "其他联系方式（如 QQ、微信等）" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, '提交' %>
  </div>
<% end %>

app/views/shops/_shop.html.erb
<div class="col-sm-6 col-md-3">
  <div class="shop">
    <div class="face">
	  <%= link_to shop_path(shop), "data-no-turbolink" => true do %>
	    <div class="cover">
	      <%= shop.name %>
	    </div>
  	    <%= image_tag shop.face.image.url(:small) %>
  	  <% end %>
    </div>
    <div class="info">
      <p class="name"><%= shop.name %></p>
      <p class="address">地址: <%= shop.address.name %></p>
      <p class="description"><%= truncate shop.description, length: 35 %></p>
    </div>
    <div class="foot-info">
  	  <p>
  	  <span class="glyphicon glyphicon-heart"></span><%= shop.likes.count %> 喜欢
	  <span class="glyphicon glyphicon-star"></span><%= shop.shop_remarks.average(:star).to_i %> 星
	  <span class="glyphicon glyphicon-comment"></span><%= shop.shop_remarks.count %> 评论
  	  </p>
    </div>
  </div>
</div>

app/views/shops/_shop_buttons.html.erb
<div class="row shop-buttons">
  <div class="col-md-12">
    <%= link_to '显示', shop, class: "btn btn-primary btn-sm" %>
    <%= link_to '管理美食', shop_foods_path(shop), class: "btn btn-primary btn-sm" %>
    <%= link_to '上传图片', uppics_shop_path(shop), class: "btn btn-primary btn-sm", "data-no-turbolink" => true %>
    <%= link_to '编辑', edit_shop_path(shop), class: "btn btn-primary btn-sm" %>
	<% if can? :destroy, shop %>
	  <%= link_to '删除', shop, class: "btn btn-primary btn-sm", method: :delete, data: { confirm: 'Are you sure?' } %>
	<% end %>
  </div>
</div>

app/views/shops/_shop_check.html.erb
<div class="col-md-12 shop" id="shop_<%= shop.id %>">
  <div class="name"><%= shop.name %></div>

  <table class="table">
	<tr>
	  <th>市县</th>
	  <th>店铺类型</th>
	  <th>地址</th>
	  <th>电话</th>
	  <th>其他</th>
	  <th>审核</th>
	</tr>
	<tr>
      <td><%= shop.area.name %></td>
      <td><%= shop.category.name %></td>
      <td><%= shop.address.name %></td>
      <td><%= shop.telephone %></td>
      <td><%= shop.contact %></td>
	  <td>
	    <%= link_to '通过', check_shop_path(shop), method: :post, remote: true, class: "btn btn-primary btn-sm" %>
        <%= link_to '不通过', check_shop_path(shop, check: "no"), method: :post, remote: true, class: "btn btn-primary btn-sm" %>
      </td>
	</tr>
  </table>

  <div class="description">本店介绍: <%= shop.description %></div>

  <div class="pictures">
	<% shop.pictures.each do |pic| %>
	  <%= image_tag pic.image.url(:small) %>
    <% end %>
	<%= "无图片" if shop.pictures.count == 0 %>
  </div>
</div>

app/views/shops/_shop_detail.html.erb
<div class="row shop-detail">

    <div class="col-md-4 shop-pictures">
      <div class="owl-carousel owl-shop-pic">
        <% shop.pictures.each do |pic| %>
          <%= image_tag pic.image.url(:small) %>
        <% end %>
      </div>
    </div>

    <div class="col-md-8">
      <ul class="shop-info">
	    <li class="shop-name"><%= shop.name %></li>
		<li class="shop-info-item">ID: <%= shop.id %> 状态: <%= Shop::STATE[shop.state] %></li>
		<li class="note">此信息由<%= shop.user.username unless shop.user.nil? %>上传</li>
        <li class="shop-info-item"><span class="item-name">店铺类型:</span><%= shop.category.name %></li>
		<li class="shop-info-item"><span class="item-name">地址:</span><%= "#{shop.area.name} | #{shop.address.name}" %></li>
        <li class="shop-info-item"><span class="item-name">联系电话:</span><%= shop.telephone %></li>
        <li class="shop-info-item"><span class="item-name">其他:</span><%= shop.contact %></li>

        <li class="shop-info-item">
		  <%= render partial: "shops/shop_buttons", locals: {shop: shop} %>
	    </li>
        <li class="shop-info-item">
          <p><span class="shop-description">本店介绍:</span><%= shop.description %></p>
	    </li>

      </ul>
    </div>

</div>

app/views/shops/_shop_pic.html.erb
<div class="col-md-3 image">
  <% if face_id == pic.id %>
    <span class="shop-face-label">封面</span>
  <% end %>
  <div class="thumbnail">
	<%= image_tag pic.image.url(:small) unless pic.image.nil? %>
  </div>
  <div class="caption actions">
    <a href="/shops/<%= @shop.id %>/face" data-picid="<%= pic.id %>" class="btn btn-primary set-face" role="button">设为封面</a>
	<a href="/pictures/<%= pic.id %>" class="btn btn-primary del-pic" data-remote role="button">删除</a>
  </div>
</div>

app/views/shops/check.js.erb
$("#shop_<%= @shop.id %>").remove();
$("#shop-count").text("<%= Shop.where(state: 0).count %>");

app/views/shops/edit.html.erb
<h1>Editing Shop</h1>

<%= render 'form' %>

<%= link_to 'Show', @shop %> |
<%= link_to 'Back', shops_path %>

app/views/shops/index.html.erb
<div class="row">
  <div class="shop-categories">
    <ul>
      <li class="category-label">分类</li>
      <% @categories.each do |c| %>
    	<li class="shop-category">
    	<% if not @category.nil? and c.id == @category.id %>
    	  <strong><%= link_to c.name, category_shops_path(c), class: "active" %></strong>
        <% else %>
    	  <%= link_to c.name, category_shops_path(c) %>
    	<% end %>
    	</li>
      <% end %>
    </ul>
  </div>
</div>
  
<div class="row">
  <%= render @shops %>
</div>

<%= will_paginate @shops, previous_label: "&laquo;", next_label: "&raquo;", renderer: BootstrapPagination::Rails %>

app/views/shops/new.html.erb
<div class="row">
  <div class="col-md-12">
	<div class="row shop-flow">
	  <div class="col-md-3"><div class="box active"><span class="number">1</span><span>填写店铺信息</span></div></div>
	  <div class="col-md-3"><div class="box"><span class="number">2</span><span>上传图片</span></div></div>
	  <div class="col-md-3"><div class="box"><span class="number">3</span><span>管理员审核</span></div></div>
	  <div class="col-md-3"><div class="box"><span class="number">4</span><span>完成</span></div></div>
	</div>
  </div>
</div>


<div class="row shop-new">
  <div class="col-md-4">
	<div>something here...</div>
  </div>
  <div class="col-md-8">
    <%= render 'form' %>
  </div>
</div>

app/views/shops/owner.html.erb
<% @shops.each do |shop| %>
  <%= render partial: "shop_detail", locals: {shop: shop} %>
<% end %>

app/views/shops/owner_shops.html.erb
<p id="notice"><%= notice %></p>

<h1>Owner Shops</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>State</th>
      <th>Area</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shops.each do |shop| %>
      <tr>
        <td><%= shop.name %></td>
        <td><%= shop.description %></td>
        <td><%= shop.state %></td>
        <td><%= shop.area %></td>
        <td><%= shop.category %></td>
        <td><%= link_to 'Show', shop %></td>
        <td><%= link_to 'Edit', edit_shop_path(shop) %></td>
        <td><%= link_to 'Destroy', shop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shop', new_shop_path %>

app/views/shops/upload_picture.js.erb
$(".shops .images").append("<%= escape_javascript(render partial:'shop_pic', locals: {face_id: @shop.face_id, pic: @picture}) %>");
$("#shop_image").val('');

app/views/shops/uppics.html.erb
<%= render "shared/goback" %>

<div class="row images">
  <%= render partial: "shop_pic", collection: @shop.pictures, as: :pic, locals: {face_id: @shop.face_id} %> 
</div>

<%= simple_form_for(@shop, url: uppics_shop_path(@shop), html: {id: :upload_shop_pics}, method: :post) do |f| %>
  <%= f.error_notification %>
  <div class="form-inputs">
    <%= f.input :image, as: :file, label: "选择上传图片" %>
  </div>
  <div class="form-actions">
    <%= f.button :submit, "上传" %>
  </div>
<% end %>