config/routes.rb
Rails.application.routes.draw do
  root 'portal_page#home'

  devise_for :users

  resources :topics do
    resources :posts
  end

  resources :posts do
    resources :comments, shallow: true
    member do
      post 'top' => "posts#top"
      post 'elite' => "posts#elite"
    end
    collection do
      get 'elite' => "posts#elite_posts"
    end
  end

  post "posts/post_pictures" => "posts#pictures"
  post "posts/:id/post_pictures" => "posts#pictures"
  post "post_pictures" => "posts#pictures"

  resources :users, only: [:index, :show]
  get "avatar" => "users#avatar"
  patch "avatar" => "users#update"

  resources :shops do
    resources :foods, shallow: true
    resources :shop_remarks, shallow: true
    member do
      get "uppics" => "shops#uppics"
      post "uppics" => "shops#upload_picture"
      post "face" => "shops#face"
      post "check" => "shops#check"
    end
    collection do
      get "owner" => "shops#owner"
    end
  end

  get "foods" => "foods#index_all"
  post "foods/:id/check" => "foods#check", as: :check_food
  post "foods/:food_id/food_remarks" => "food_remarks#create", as: :food_food_remarks
  delete "food_remarks/:id" => "food_remarks#destroy", as: :food_remark
  resources :remarks

  get "category/:category_id/shops" => "shops#index", as: :category_shops

  resources :pictures, only: [:destroy]

  namespace :admin do
    get 'manage/check'
    get 'manage/shops'
  end

  post "shops/likes/:likable_id/:likable_type" => "likes#create", as: :shop_likes
  post "foods/likes/:likable_id/:likable_type" => "likes#create", as: :food_likes

end

app/models/ability.rb
class Ability
  include CanCan::Ability


  def initialize(user)
    # Define abilities for the passed in user here. For example:
    
    user ||= User.new # guest user (not logged in)

    alias_action :create, :read, :update, :destroy, :to => :crud

    # all role methods are defined User model
    # ["guest", "common_user", "merchant", "bbs_admin", "admin", "supper_admin"]
    if user.supper_admin?
      can :manage, :all
    elsif user.bbs_admin?
      can :read, :all
      can :index_all, Food
      can :elite_posts, Post
      can :crud, [Post, Comment]
      can [:top, :elite], [Post]
    elsif user.common_user?
      can :read, :all
      can :elite_posts, Post
      can [:create, :pictures], [Post, Comment]

      can [:update], Post do |post|
        !post.user_id.nil? and post.user_id == user.id
      end
      can [:update, :destroy], Comment do |post|
        !post.user_id.nil? and post.user_id == user.id
      end

      can :create, ShopRemark
      can :destroy, ShopRemark do |remark|
        !remark.user_id.nil? and remark.user_id == user.id
      end

      can [:create, :uppics], Shop
      can [:owner, :update, :upload_picture, :face], Shop do |shop|
        !shop.user_id.nil? and shop.user_id == user.id
      end

      can [:create, :index_all], Food
      can [:update, :destroy], Food do |food|
        !food.user_id.nil? and food.user_id == user.id
      end

      can :create, Picture
      can [:update, :destroy], Picture do |pic|
        !pic.user_id.nil? and pic.user_id == user.id
      end

    else
      can :read, :all
      can :index_all, Food
      can :elite_posts, Post
    end

    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/address.rb
class Address < ActiveRecord::Base
  validates :name, presence: true

  belongs_to :shop
end

app/models/area.rb
class Area < ActiveRecord::Base
  validates :name, presence: true

  has_many :shops, dependent: :nullify
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, :kind, presence: true

  has_many :shops, -> { where.not state: 0 }, dependent: :nullify

  # kind 1: shops
  CATEGORY_KIND = {shop: 1}

  scope :shop_categories, -> { where kind: 1 }

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post, counter_cache: true

  validates :content, presence: true

  # will_paginate
  self.per_page = 30
end

app/models/food.rb
class Food < ActiveRecord::Base
  validates :name, :description, :unit, :price, :state, presence: true
  validates :price, numericality: true

  belongs_to :shop
  belongs_to :user
  has_one :picture, as: :imageable, dependent: :destroy
  has_many :food_remarks, dependent: :destroy
  has_many :likes, as: :likable, dependent: :destroy

  accepts_nested_attributes_for :picture

  default_scope -> { order created_at: :desc }

  STATE = ["待审核", "通过", "不通过"]

  # will_paginate
  self.per_page = 100
end

app/models/food_remark.rb
class FoodRemark < ActiveRecord::Base
  belongs_to :food
  belongs_to :user

  # will_paginate
  self.per_page = 30
end

app/models/like.rb
class Like < ActiveRecord::Base
  validates :user_id, :likable_id, :likable_type, presence: true

  belongs_to :user
  belongs_to :likable, polymorphic: true

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  has_attached_file :image, styles: { large: "1000x1000>", medium: "800x600#", small: "300x300#" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  belongs_to :imageable, polymorphic: true
  has_one :shop, foreign_key: :face_id, dependent: :nullify
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :topic
  belongs_to :user
  has_many :comments, dependent: :destroy

  validates :title, :content, :topic, :user_id, presence: true
  validates :title, length: {maximum: 50}

  default_scope { order(top: :desc, created_at: :desc) }

  # will_paginate
  self.per_page = 30
end

app/models/remark.rb
class Remark < ActiveRecord::Base
  validates :content, :user_id, :remarkable_id, :remarkable_type, presence: true

  belongs_to :user
  belongs_to :remarkable, polymorphic: true
end

app/models/shop.rb
class Shop < ActiveRecord::Base
  validates :name, :description, :state, :user_id, :area_id,
            :category_id, presence: true

  belongs_to :area
  belongs_to :user
  belongs_to :category, -> { where kind: Category::CATEGORY_KIND[:shop] }
  belongs_to :face, class_name: "Picture", foreign_key: :face_id, dependent: :destroy
  has_many :foods, -> { where state: 1 }, dependent: :destroy
  has_one :address,  dependent: :destroy
  has_many :pictures, as: :imageable, dependent: :destroy
  has_many :shop_remarks, dependent: :destroy
  has_many :likes, as: :likable, dependent: :destroy

  accepts_nested_attributes_for :address

  default_scope -> { order created_at: :desc }

  STATE = ["待审核", "正常"]

  # will_paginate
  self.per_page = 100
end

app/models/shop_remark.rb
class ShopRemark < ActiveRecord::Base
  belongs_to :shop
  belongs_to :user

  # will_paginate
  self.per_page = 30
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  validates :name, presence: true

  has_many :posts, dependent: :nullify
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username, presence: true, length: {maximum: 10}, uniqueness: true;

  has_many :posts, dependent: :nullify
  has_many :comments, dependent: :nullify
  has_many :pictures, as: :imageable, dependent: :destroy
  has_many :shops, dependent: :nullify
  has_many :foods, dependent: :nullify
  has_many :shop_remarks, dependent: :nullify
  has_many :food_remarks, dependent: :nullify
  has_many :likes, dependent: :destroy

  # user roles
  ROLES = ["guest", "common_user", "merchant", "bbs_admin", "admin", "supper_admin"]

  ROLES.each do |role|
    define_method("#{role}?") { role == ROLES[self.role] }
  end

  # paperclip settings
  has_attached_file :avatar, styles: { medium: "300x300#", thumb: "100x100#" }, default_url: ":style/avatar.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/shared/_foot.html.erb
<div class="container-fluid">
  <div class="row foot">
	<div class="col-md-12">
	  <ul>
	    <li>广告合作</li>
	    <li>联系我们</li>
	    <li>关于我们</li>
		<li><%= link_to '免责声明', post_path(1, show_as_article: true) %> </li>
	    <li>官方QQ群: 531603422</li>
	  </ul>
	</div>
	<div class="col-md-12 copy-right">
	  Copyright © 2016 美食文山 版权所有 powered by www.FoodWS.com
	</div>
  </div>
</div>

app/views/shared/_goback.html.erb
<div class="row">
  <div class="col-md-12">
    <p class="goback"><%= link_to '返回', :back %></p>
  </div>
</div>

app/views/shared/_headbar.html.erb
<div class="fixed-top">
<%= render 'shared/headline' %>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
		<!--
		<a class="navbar-brand logo" href="http://www.foodws.com">美食汇</a>
		-->
		<div class="logo">
		<%= image_tag 'logo.png' %>
		</div>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
		  <li><%= link_to "首页", root_path %></li>
		  <li><%= link_to "社区", posts_path %></li>
          <li><%= link_to "商家", shops_path %></li>
          <li><%= link_to "美食", foods_path %></li>
		  <li class="disabled"><a href="#">集市</a></li>
	    </ul>

        <ul class="nav navbar-nav navbar-right login">
		  <% if user_signed_in? %>
		    <li><%= link_to '新建店铺', new_shop_path %></li>
			<li>
		      <% if current_user.shops.any? %>
				<%= link_to '我的店铺', owner_shops_path %>
			  <% end %>
			</li>
			<li></li>
			<% if current_user.supper_admin? %>
			  <li><%= link_to '管理店铺', admin_manage_shops_path %></li>
			  <li><%= link_to '审核', admin_manage_check_path %></li>
			<% end %>
		    <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
				<span class="glyphicon glyphicon-user" aria-hidden="true"></span> 
                <%= current_user.username %>
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
				<li><%= link_to '我的主页', user_path(current_user) %></li>
				<li><%= link_to '修改头像', avatar_path %></li>
				<li><%= link_to '修改基本信息', edit_user_registration_path %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to '退出', destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>
		  <% else %>
			  <li><%= link_to '登录', new_user_session_path %></li>
			  <li><%= link_to '注册', new_user_registration_path %></li>
		  <% end %>
        </ul>
      </div>
    </div>
  </div>
</nav>

</div>

app/views/shared/_headline.html.erb
<div class="container-fluid headline">
  <div class="container">
    <div class="headline-links pull-right">
	  美食汇-文山人自己的美食网站！ 
	  www.FoodWS.com 
  	  <a href=#>关于我们</a>
    </div>
  </div>
</div>