config/routes.rb
Rails.application.routes.draw do
  root 'portal_page#home'

  devise_for :users

  resources :topics do
    resources :posts
  end

  resources :posts do
    resources :comments, shallow: true
    member do
      post 'top' => "posts#top"
      post 'elite' => "posts#elite"
    end
    collection do
      get 'elite' => "posts#elite_posts"
    end
  end

  post "posts/post_pictures" => "posts#pictures"
  post "posts/:id/post_pictures" => "posts#pictures"
  post "post_pictures" => "posts#pictures"

  resources :users, only: [:index, :show]
  get "avatar" => "users#avatar"
  patch "avatar" => "users#update"

  resources :shops do
    resources :foods, shallow: true
    resources :shop_remarks, shallow: true
    member do
      get "uppics" => "shops#uppics"
      post "uppics" => "shops#upload_picture"
      post "face" => "shops#face"
      post "check" => "shops#check"
    end
    collection do
      get "owner" => "shops#owner"
    end
  end

  get "foods" => "foods#index_all"
  post "foods/:id/check" => "foods#check", as: :check_food
  post "foods/:food_id/food_remarks" => "food_remarks#create", as: :food_food_remarks
  delete "food_remarks/:id" => "food_remarks#destroy", as: :food_remark
  resources :remarks

  get "category/:category_id/shops" => "shops#index", as: :category_shops

  resources :pictures, only: [:destroy]

  namespace :admin do
    get 'manage/check'
    get 'manage/shops'
  end

  post "shops/likes/:likable_id/:likable_type" => "likes#create", as: :shop_likes
  post "foods/likes/:likable_id/:likable_type" => "likes#create", as: :food_likes

end

app/models/food.rb
class Food < ActiveRecord::Base
  validates :name, :description, :unit, :price, :state, presence: true
  validates :price, numericality: true

  belongs_to :shop
  belongs_to :user
  has_one :picture, as: :imageable, dependent: :destroy
  has_many :food_remarks, dependent: :destroy
  has_many :likes, as: :likable, dependent: :destroy

  accepts_nested_attributes_for :picture

  default_scope -> { order created_at: :desc }

  STATE = ["待审核", "通过", "不通过"]

  # will_paginate
  self.per_page = 100
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: [:show, :edit, :update, :destroy]
  before_action :set_shop, only: [:index, :new, :create]
  before_action :authenticate_user!, except: [:index_all, :show]

  # cancancan
  load_and_authorize_resource

  layout "foods_layout"

  # GET /foods
  # GET /foods.json
  def index
    @foods = Food.where(shop_id: @shop.id).order created_at: :desc
  end

  def index_all
    @foods = Food.where(state: 1).paginate(:page => params[:page])
  end

  # GET /foods/1
  # GET /foods/1.json
  def show
    @remarks = @food.food_remarks.order(created_at: :desc).paginate(:page => params[:page])
  end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit
  end

  # POST /foods
  # POST /foods.json
  def create
    @food = Food.new(food_params.merge shop_id: params[:shop_id], user_id: current_user.id, state: 0) # 0 means invalid

    respond_to do |format|
      if @food.save
        format.html { redirect_to shop_foods_path(@shop), notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1
  # PATCH/PUT /foods/1.json
  def update
    respond_to do |format|
      # if food is passed, won't check it again.
      if @food.state == 1
        state = 1 
      else
        state = 0
      end

      if @food.update(food_params.merge state: state) # 1 means valid
        format.html { redirect_to @food, notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1
  # DELETE /foods/1.json
  def destroy
    @food.destroy
    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def check
    if params[:check].nil?
      @food.update state: 1
    elsif params[:check] == "no"
      @food.update state: 2
    end
    respond_to do |format|
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food
      @food = Food.find(params[:id])
    end

    def set_shop
      @shop = Shop.find params[:shop_id]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_params
      params.require(:food).permit(:user_id, :shop_id, :name, :description, :state, :unit, :price, :discount_price, picture_attributes: [:image])
    end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_food.html.erb
<div class="col-sm-6 col-md-3">
  <div class="food">
    <div class="picture">
  	<%= link_to food_path(food) do %>
  	  <%= image_tag food.picture.image.url(:small) %>
  	<% end %>
    </div>
    <div class="info">
      <p class="name"><%= food.name %></p>
      <p class="description"><%= truncate food.description, length: 35 %></p>
	  <p class="price">
	    <%= render partial: "/foods/food_price", locals: {food: food} %>
	  </p>
    </div>
    <div class="foot-info">
  	  <p>
	  <span class="glyphicon glyphicon-heart"></span><%= food.likes.count %> 喜欢
	  <span class="glyphicon glyphicon-star"></span><%= food.food_remarks.average(:star).to_i %> 星
  	  <span class="glyphicon glyphicon-comment"></span><%= food.food_remarks.count %> 评论
  	  </p>
    </div>
  </div>
</div>

app/views/foods/_food_check.html.erb
<div class="col-md-12 food" id="food_<%= food.id %>">
  <table class="table">
	<tr>
	  <th>图片</th>
	  <th>名称</th>
	  <th>介绍</th>
	  <th>价格</th>
	  <th>审核</th>
	</tr>
	<tr>
      <td class="pictures">
        <% if food.picture.nil? %>
          <%= "无图片" %>
        <% else %>
          <%= image_tag food.picture.image.url(:small) %>
        <% end %>
      </td>
      <td><%= food.name %></td>
	  <td><%= "#{food.price}元/#{food.unit}" %></td>
      <td><%= truncate food.description, length: 35 %></td>
	  <td>
	    <%= link_to '通过', check_food_path(food), method: :post, remote: true, class: "btn btn-primary btn-sm" %>
        <%= link_to '不通过', check_food_path(food, check: "no"), method: :post, remote: true, class: "btn btn-primary btn-sm" %>
      </td>
	</tr>
  </table>

</div>

app/views/foods/_food_item.html.erb
<div class="food-item">
<div class="media">
  <div class="media-left">
    <%= image_tag food.picture.image.url(:small) unless food.picture.nil? %>
  </div>
  <div class="media-body">
	<ul>
	  <li>名称: <%= food.name %></li>
      <li>介绍: <%= food.description %></li>
	  <li>状态: <%= Food::STATE[food.state] %></li>
	  <li>时间: <%= food.created_at.to_s :db %></li>
      <li><%= link_to '显示', food %></li>
      <li><%= link_to '编辑', edit_food_path(food) %></li>
      <li><%= link_to '删除', food, method: :delete, data: { confirm: 'Are you sure?' } %></li>
	</ul>
  </div>

</div>

app/views/foods/_food_price.html.erb
<% unless food.discount_price.nil? %>
	<span class="discount-price"><%= "#{food.discount_price}元/#{food.unit}" %></span>
	<span class="discounted"><%= "#{food.price}元/#{food.unit} " %></span>
<% else %>
	<%= "#{food.price}元/#{food.unit} " %>
<% end %>

app/views/foods/_food_strip.html.erb
<div class="col-sm-6">
    <div class="row food-strip">
  
  	  <div class="col-md-4 picture">
	    <%= link_to food_path(food), "data-no-turbolink" => true do %>
          <%= image_tag food.picture.image.url(:small) %>
        <% end %>
  	  </div>
  
  	  <div class="col-md-8 info">
        <p class="name"><%= food.name %></p>

	    <div class="stars">
	      <span class="spec name">星级:</span> 
	      <% food.food_remarks.average(:star).to_i.downto 1 do %>
            <span class="button star glyphicon glyphicon-star"></span>
	      <% end %>
	      <% food.food_remarks.average(:star).to_i.upto 4 do %>
            <span class="button star-empty glyphicon glyphicon-star"></span>
	      <% end %>
	    </div>

	    <p class="price">
	      <%= render partial: "/foods/food_price", locals: {food: food} %>
	    </p>
  
        <div class="foot-info">
		  <span class="glyphicon glyphicon-heart"></span><%= food.likes.count %> 喜欢 
          <span class="glyphicon glyphicon-comment"></span><%= food.food_remarks.count %> 评论
        </div>
      </div>
  
  </div>
</div>

app/views/foods/_form.html.erb
<%= simple_form_for [@shop, @food] do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, label: "名称" %>
	<%= f.input :unit, label: "单位(如:盘、个、份等)" %>
	<%= f.input :price, label: "价格(数字， 如100.5)" %>
    <%= f.input :discount_price, label: "优惠价(可选)" %>
    <%= f.input :description, label: "美食介绍" %>

	<%= f.simple_fields_for :picture_attributes, @food.picture do |fd| %>
      <%= fd.input :image, as: :file, label: "选择上传图片" %>
	<% end %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/foods/check.js.erb
$("#food_<%= @food.id %>").remove();
$("#food-count").text("<%= Food.where(state: 0).count %>");

app/views/foods/edit.html.erb
<h1>Editing Food</h1>

<%= render 'form' %>

<%= link_to 'Show', @food %> |
<%= link_to 'Back', foods_path %>

app/views/foods/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to '添加美食', new_shop_food_path(@shop), class: "btn btn-primary btn-sm" %>

<%= render partial: "food_item", collection: @foods, as: :food %>

app/views/foods/index_all.html.erb
<div class="row">
  <div class="col-md-12">
    <p class="head-banner">placeholder ....</p>
  </div>
</div>

<div class="row">
  <%= render @foods %>
</div>

<%= will_paginate @foods, previous_label: "&laquo;", next_label: "&raquo;", renderer: BootstrapPagination::Rails %>

app/views/foods/new.html.erb
<h1>New Food</h1>

<%= render 'form' %>

<%= link_to 'Back', foods_path %>

app/views/foods/show.html.erb
<div class="row food-show">

  <div class="col-md-9">


	<div class="food-info">
      <div class="food-name"><%= @food.name %></div>
	  <div class="spec star">
		<span class="spec name">星级:</span> 
		<% @food.food_remarks.average(:star).to_i.downto 1 do %>
          <span class="button star glyphicon glyphicon-star"></span>
		<% end %>
		<% @food.food_remarks.average(:star).to_i.upto 4 do %>
          <span class="button star-empty glyphicon glyphicon-star"></span>
		<% end %>
	  </div>
	  <div class="spec"><span class="spec-name">价格:</span>
	    <span class="item"><%= render partial: "food_price", locals: {food: @food} %></span>
        <span class="spec-name">喜欢:</span>
		<span id="Food<%=@food.id %>_likecount"><%= @food.likes.count %></span> 喜欢
        <%= link_to food_likes_path(@food.id, "Food"), method: :post, remote: true, class: "like" do %>
		  <span class="glyphicon glyphicon-heart-empty"></span>
		<% end %>
	  </div>

      <div class="shop-info">
	    <div class="shop-name">
		  <span>商家:</span><%= link_to @food.shop.name, shop_path(@food.shop) %>
	    </div>
	    <div class="relation">
	    	<span>地址:</span><%= @food.shop.address.name %>
          <span>联系电话:</span><%= @food.shop.telephone %>
          <span>其他:</span><%= @food.shop.contact %>
	    </div>
	  </div>

      <div class="food-picture">
        <%= image_tag @food.picture.image.url(:large) %>
      </div>

	  <div class="food-description">
	    <p class="introduce">美食介绍:</p>
	    <%= @food.description %>
	  </div>

	  <div class="food-info-item share">分享链接</div>
	</div>

    <div class="food-remarks">
      <% if user_signed_in? %>
        <%= render partial: 'food_remarks/form', locals: {food: @food} %>
      <% else %>
        <%= link_to '登录点评店铺', new_user_session_path %>
      <% end %>
      <%= render @remarks %>
	  <%= will_paginate @remarks, previous_label: "&laquo;", next_label: "&raquo;", renderer: BootstrapPagination::Rails %>
    </div>

  </div>

  <div class="col-md-3">
    placeholder...
  </div>
</div>