config/routes.rb
Rails.application.routes.draw do
  root 'portal_page#home'

  devise_for :users

  resources :topics do
    resources :posts
  end

  resources :posts do
    resources :comments, shallow: true
    member do
      post 'top' => "posts#top"
      post 'elite' => "posts#elite"
    end
    collection do
      get 'elite' => "posts#elite_posts"
    end
  end

  post "posts/post_pictures" => "posts#pictures"
  post "posts/:id/post_pictures" => "posts#pictures"
  post "post_pictures" => "posts#pictures"

  resources :users, only: [:index, :show]
  get "avatar" => "users#avatar"
  patch "avatar" => "users#update"

  resources :shops do
    resources :foods, shallow: true
    resources :shop_remarks, shallow: true
    member do
      get "uppics" => "shops#uppics"
      post "uppics" => "shops#upload_picture"
      post "face" => "shops#face"
      post "check" => "shops#check"
    end
    collection do
      get "owner" => "shops#owner"
    end
  end

  get "foods" => "foods#index_all"
  post "foods/:id/check" => "foods#check", as: :check_food
  post "foods/:food_id/food_remarks" => "food_remarks#create", as: :food_food_remarks
  delete "food_remarks/:id" => "food_remarks#destroy", as: :food_remark
  resources :remarks

  get "category/:category_id/shops" => "shops#index", as: :category_shops

  resources :pictures, only: [:destroy]

  namespace :admin do
    get 'manage/check'
    get 'manage/shops'
  end

  post "shops/likes/:likable_id/:likable_type" => "likes#create", as: :shop_likes
  post "foods/likes/:likable_id/:likable_type" => "likes#create", as: :food_likes

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :topic
  belongs_to :user
  has_many :comments, dependent: :destroy

  validates :title, :content, :topic, :user_id, presence: true
  validates :title, length: {maximum: 50}

  default_scope { order(top: :desc, created_at: :desc) }

  # will_paginate
  self.per_page = 30
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # because cancancan already autoload @post, so comment the following line
  # before_action :set_post, only: [:show, :edit, :update, :destroy]

  layout "post_layout"

  # cancancan
  load_and_authorize_resource


  # GET /posts
  # GET /posts.json
  def index
    @topics = Topic.all

    if params[:topic_id].nil?
      @posts = Post.paginate(:page => params[:page])
    elsif
      @active_topic = Topic.find(params[:topic_id])
      # @posts = @active_topic.posts
      @posts = Post.where(topic_id: @active_topic.id).paginate(:page => params[:page])

    end
  end

  # get /posts/elite
  def elite_posts
    @topics = Topic.all
    @posts = Post.where(elite: true).paginate(:page => params[:page])
    render :index
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post.display_count += 1
    @post.save
    @comments = Comment.where(post_id: @post.id).paginate(:page => params[:page])

    # calculate reply number
    page = params[:page].to_i
    page = (page <= 0) ? 0 : (page - 1)
    @floor = page * Comment.per_page

    respond_to do |format|
      unless params[:show_as_article].nil?
        format.html { render :show_as_article }
      else
        format.html { render :show }
      end
      format.js
    end
  end

  # GET /posts/new
  def new
    if user_signed_in?
      @post = Post.new
    else
      redirect_to new_user_session_path
    end
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    params_with_userid = post_params
    params_with_userid[:user_id] = current_user.id
    @post = Post.new(params_with_userid)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        response.location = "posts/new"
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # upload picture
  def pictures
    picture = current_user.pictures.build image: params[:image_file]
    if picture.save
      result = { success: true,
                 file_path: picture.image.url(:large)
               }
      render json: result.to_json
    else
      result = { success: false,
                 msg: "图片上传失败",
                 file_path: ""
               }
      render json: result.to_json
    end
  end

  # posts/1/top
  def top
    @post.update top: (@post.top? ? 0 : 1)
  end

  # posts/1/elite
  def elite
    @post.update elite: (@post.elite? ? 0 : 1)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :topic_id, :user_id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
  <%#= f.error_notification %>

<div class="panel panel-default">
  <div class="panel-heading">请选择一个话题，并输入帖子标题.</div>
  <div class="panel-body">
    <%= f.association :topic, label: false %>
    <%= f.input :title, placeholder: "标题", label: false %>
  </div>
</div>

  <div class="form-inputs">
    <%= f.input :content, label: false, autofocus: true %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, (@post.new_record? ? "发 布" : "编 辑")%>
  </div>
<% end %>

<script type="text/javascript">
  var editor = new Simditor({
    textarea: $('#post_content'),
    toolbar: [ 'title','bold','italic','underline','strikethrough','color','|',
             'ol','ul','blockquote','code','table','link','image','hr' ],
    pasteImage: true,
    defaultImage: '<%= image_path "upload-loading.png" %>',
    upload: {
              url: 'post_pictures',
              params: null,
              fileKey: 'image_file',
              connectionCount: 3,
              leaveConfirm: '图片已上传,确定要离开吗?'
            }
    });
</script>

app/views/posts/_post_info.html.erb
<span class="topic"><%= post.topic ? post.topic.name : "未知" %></span>
 • <%= post.user ? post.user.username : "用户已注销" %>
 • <span>发表于 <time class="timeago" datetime="<%= post.created_at.to_formatted_s(:iso8601) %>"></time></span>
 <% unless post.comments.last.nil? %> <!-- 这里有性能问题 -->
 • <%= post.comments.last.user ? post.comments.last.user.username : "用户已注销" %>
 • <span>回复于 <time class="timeago" datetime="<%= post.comments.last.created_at.to_formatted_s(:iso8601) %>"></time></span>
 • <% end %>
 <span>浏览 <%= post.display_count %>次</span>
 • <%= link_to('编辑', edit_post_path(post)) if can? :update, post %>
 <%= link_to('删除', post, method: :delete, data: { confirm: '你确定要删除?' }) if can? :destroy, post %>

 <% if can? [:top, :elite], post %>
   • <%= link_to top_post_path(post), {method: :post, remote: true}, title: "置顶" do %>
     <span class="glyphicon glyphicon-pushpin"></span>
   <% end %>
   <%= link_to elite_post_path(post), {method: :post, remote: true}, title: "精华" do %>
     <span class="glyphicon glyphicon-thumbs-up"></span>
   <% end %>
 <% end %>

app/views/posts/_post_list.html.erb
<div class="article-list">
  <div class="article-list-info"><%= post.created_at.to_s(:db) %></div>
  <div class="article-list-title"><%= link_to post.title, post_path(post, show_as_article: true), 'data-no-turbolink' => true %></div>
</div>

app/views/posts/_sidebar.html.erb
<% content_for :sidebar do %>
<div class="panel panel-default">
  <div class="panel-heading">发布帖子</div>
  <ul class="list-group">
    <li class="list-group-item">
      <%= link_to '发布帖子', new_post_path, class: "btn btn-danger" %>
	</li>
  </ul>
</div>

<div class="panel panel-default">
  <div class="panel-heading">社区信息</div>
  <ul class="list-group">
    <li class="list-group-item">社区人数: <span><%= User.count %> 人</span></li>
    <li class="list-group-item">帖子数: <span><%= Post.count %> 帖</span></li>
    <li class="list-group-item">回帖数: <span><%= Comment.count %> 条</span></li>
  </ul>
</div>

<div class="panel panel-default">
  <div class="panel-heading">友情链接</div>
  <ul class="list-group">
	<li class="list-group-item"><a href="#">文山美食</a></li>
	<li class="list-group-item"><a href="#">文山美食</a></li>
	<li class="list-group-item"><a href="#">文山美食</a></li>
  </ul>
</div>
<% end %>

app/views/posts/edit.html.erb
<% content_for :pathlink do %>
  <ol class="breadcrumb">
	<li><%= link_to "首页", root_path %></li>
    <li><%= link_to "社区", posts_path %></li>
	<% unless @post.topic.nil? %>
      <li><%= link_to @post.topic.name, "/topic/#{@post.topic.id}/posts" %></li>
	<% end %>
    <li class="active">编辑帖子</li>
  </ol>
<% end %>

<%= render 'sidebar' %>

<%= render 'form' %>

app/views/posts/elite.js.erb
var link = "<%= escape_javascript(link_to @post.title, @post, 'data-no-turbolink' => true) %>";
<% if @post.top? %>
  link += "<span class='glyphicon glyphicon-pushpin'></span>";
<% end %>
<% if @post.elite? %>
  link += "<span class='glyphicon glyphicon-thumbs-up'></span>";
<% end %>

$("#post_<%= @post.id %>").empty().append(link);

app/views/posts/index.html.erb
<% content_for :pathlink do %>
  <ol class="breadcrumb">
	<li><%= link_to "首页", root_path %></li>
    <li><%= link_to "社区", posts_path %></li>
    <li class="active">全部话题</li>
  </ol>
<% end %>

<%= render 'sidebar' %>

<div class="panel panel-default">
  <div class="panel-heading">
    <ul class="nav nav-pills">
	  <li role="presentation" class="<%= "active" if @active_topic.nil? and action_name == "index" %>" >
		<%= link_to "全部话题", posts_path %>
	  </li>
	  <li role="presentation" class="<%= "active" if @active_topic.nil? and action_name == "elite_posts" %>" >
	    <%= link_to "精华", elite_posts_path %>
	  </li>
      <% @topics.each do |topic| %>
		<li role="presentation" class="<%= "active" if ! @active_topic.nil? and @active_topic.id == topic.id %>">
		  <%= link_to topic.name, topic_posts_path(topic.id) %>
		</li>
      <% end %>
    </ul>
  </div>

  <ul class="list-group">
    <% @posts.each do |post| %>
      <li class="list-group-item">
        <div class="media">
          <div class="media-left">
		  <% unless post.user.nil? %>
  		    <%= link_to user_path(post.user) do %>
              <%= image_tag post.user.avatar.url(:thumb), class: "avatar" %>
  		    <% end %>
		  <% else %>
            <%= image_tag "thumb/avatar.png", class: "avatar" %>
  		  <% end %>
          </div>
          <div class="media-body">
		  <p class="media-heading post-list-head" id="post_<%= post.id %>">
  			<%= link_to post.title, post, 'data-no-turbolink' => true %>
			<% if post.top? %>
			  <span class="glyphicon glyphicon-pushpin"></span>
			<% end %>
			<% if post.elite? %>
		      <span class="glyphicon glyphicon-thumbs-up"></span>
			<% end %>
  		  </p>
  		  <p class="post-list-info">
  		    <%= render partial: 'post_info', locals: {post: post} %>
  		  </p>
          </div>
  		<div class="media-right">
  		  <div class="replys-box">
  		    <p>回复</p><p class="number"><%= post.comments.size %></p>
  		  </div>
  		</div>
        </div>
      </li>
    <% end %>
  </ul>
</div>
<%= will_paginate @posts, previous_label: "&laquo;", next_label: "&raquo;", renderer: BootstrapPagination::Rails %>

<!-- translate time to words -->
<script type="text/javascript">
  jQuery("time.timeago").timeago();
</script>

app/views/posts/new.html.erb
<% content_for :pathlink do %>
  <ol class="breadcrumb">
	<li><%= link_to "首页", root_path %></li>
    <li><%= link_to "社区", posts_path %></li>
    <li class="active">发布帖子</li>
  </ol>
<% end %>

<%= render 'sidebar' %>

<%= render 'form' %>

app/views/posts/show.html.erb
<% content_for :pathlink do %>
  <ol class="breadcrumb">
	<li><%= link_to "首页", root_path %></li>
    <li><%= link_to "社区", posts_path %></li>
	<% unless @post.topic.nil? %>
      <li><%= link_to @post.topic.name, topic_posts_path(@post.topic.id) %></li>
	<% end %>
    <li class="active">浏览帖子</li>
  </ol>
<% end %>

<%= render 'sidebar' %>

<div class="panel panel-default">
  <div class="panel-heading">
    <div class="media">
	  <div class="media-body">
	    <h4 class="post-show-title" id="post_<%= @post.id %>">
		  <%= @post.title %>
		  <% if @post.top? %>
		    <span class="glyphicon glyphicon-pushpin"></span>
		  <% end %>
		  <% if @post.elite? %>
	        <span class="glyphicon glyphicon-thumbs-up"></span>
		  <% end %>
	    </h4>
        <p class="post-show-info">
          <%= render partial: 'post_info', locals: {post: @post} %>
	    </p>
	  </div>
      <div class="media-right">
		<% unless @post.user.nil? %>
  		  <%= link_to user_path(@post.user) do %>
            <%= image_tag @post.user.avatar.url(:thumb), class: "avatar" %>
  		  <% end %>
		<% else %>
          <%= image_tag "thumb/avatar.png", class: "avatar" %>
  		<% end %>
      </div>
    </div>
  </div>
  <div class="panel-body">
    <%= raw @post.content %>
  </div>
</div>

<%= render "comments/comments" %>

<% if user_signed_in? %>
  <%= render partial: "comments/form", locals: {post: @post} %>
<% elsif %>
  <p class="text-center">登录后可以参与回复. <%= link_to '登录', new_user_session_path %></p>
<% end %>

app/views/posts/show.js.erb
$("#comments").replaceWith("<%= escape_javascript(render "comments/comments") %>");

app/views/posts/show_as_article.html.erb
<div class="hold-bar"></div>
<div class="panel panel-default article">
  <div class="panel-heading">
    <div class="media">
	  <div class="media-body">
        <h4 class="post-show-title"><%= @post.title %></h4>
        <p class="post-show-info">
          <span class="topic"><%= @post.topic ? @post.topic.name : "未知" %></span>
           • <%= @post.user ? @post.user.username : "用户已注销" %>
           • <span>发表于 <time class="timeago" datetime="<%= @post.created_at.to_formatted_s(:iso8601) %>"></time></span>
           <span>浏览 <%= @post.display_count %>次</span>
           • <%= link_to('编辑', edit_post_path(@post)) if can? :update, @post %>
           <%= link_to('删除', @post, method: :delete, data: { confirm: '你确定要删除?' }) if can? :destroy, @post %>
	    </p>
	  </div>
      <div class="media-right">
		<% unless @post.user.nil? %>
  		  <%= link_to user_path(@post.user) do %>
            <%= image_tag @post.user.avatar.url(:thumb), class: "avatar" %>
  		  <% end %>
		<% else %>
          <%= image_tag "thumb/avatar.png", class: "avatar" %>
  		<% end %>
      </div>
    </div>
  </div>
  <div class="panel-body">
    <%= raw @post.content %>
  </div>
</div>

<!-- translate time to words -->
<script type="text/javascript">
  jQuery("time.timeago").timeago();
</script>

<% content_for :sidebar do %>
<div class="hold-bar"></div>
<div class="panel panel-default">
  <div class="panel-heading">小常识</div>
  <div class="panel-body">
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">广告</div>
  <div class="panel-body">
  </div>
</div>
<% end %>

app/views/posts/top.js.erb
var link = "<%= escape_javascript(link_to @post.title, @post, 'data-no-turbolink' => true) %>";
<% if @post.top? %>
  link += "<span class='glyphicon glyphicon-pushpin'></span>";
<% end %>
<% if @post.elite? %>
  link += "<span class='glyphicon glyphicon-thumbs-up'></span>";
<% end %>

$("#post_<%= @post.id %>").empty().append(link);